[project]
name = "Calculator"
version = "0.1.0"
description = "Simple calculator implemented to see how mcp works"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.8.0",
]
